import types

class Controls:
    def __init__(self, picam2, controls={}) -> None: ...
    def __setattr__(self, name, value) -> None: ...
    def __getattribute__(self, name): ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, tb: types.TracebackType | None) -> None: ...
    def set_controls(self, controls) -> None: ...
    def get_libcamera_controls(self): ...
    def make_dict(self): ...
