from _typeshed import Incomplete
from picamera2.encoders.encoder import Encoder as Encoder

class MultiEncoder(Encoder):
    threads: Incomplete
    tasks: Incomplete
    def __init__(self, num_threads: int = 4) -> None: ...
    def output_thread(self) -> None: ...
    def do_encode(self, request, stream): ...
    def encode_func(self, request, name): ...
